#!/bin/sh

##
# Generate ${PREFIX}/devenv.sh
#
# This shell script can be sources
#
#	. PREFIX/devenv.sh
#
# to setup environment in order to use built toolchain.
#

devenv() {
	cat <<-EOF >${PREFIX}/devenv.sh
		#!/bin/sh

		# devenv.sh generated by build.sh
		#
		# to be installed in ${PREFIX}

		PATH=${PREFIX}/sbin:${PREFIX}/bin:\${PATH}

		export MANPATH=${PREFIX}/share/man:/usr/local/share/man:/usr/share/man
		export INFOPATH=${PREFIX}/share/info:/usr/local/share/info:/usr/share/info

		if test -f ${PREFIX}/share/config.site; then
			export CONFIG_SITE=${PREFIX}/share/config.site
		fi

		if test ! -x ${PREFIX}/bin/pkgconf && test ! -x ${PREFIX}/bin/pkg-config; then
			export PKG_CONFIG_LIBDIR=${PREFIX}/${arch_libdir}/pkgconfig:${PREFIX}/lib/pkgconfig:${PREFIX}/share/pkgconfig
		fi

		export CMAKE_PREFIX_PATH=${PREFIX}
		export CMAKE_GENERATOR='Unix Makefile'
	EOF
}
